-- Data export generated by export-db script
-- Date: 2026-06-08T20:20:52.023Z

-- bot_state (1 rows)
INSERT INTO bot_state (id, running, current_account_id, started_at, updated_at) VALUES (1,f,,,2026-06-08 19:59:27.603067+00) ON CONFLICT DO NOTHING;
