-- Schema export generated by export-db script
-- Date: 2026-06-08T20:20:51.098Z

--
-- PostgreSQL database dump
--

\restrict evt5EBCNejPMFOSBNXeLMLQsTxm7FXqK6rNVOHh2SpKEZJpQdM2Uxt4scqTqRPJ

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id integer NOT NULL,
    phone text NOT NULL,
    label text,
    status text DEFAULT 'active'::text NOT NULL,
    session_string text,
    joined_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    joined_today integer DEFAULT 0 NOT NULL,
    daily_limit integer DEFAULT 85 NOT NULL,
    current_delay integer DEFAULT 1030 NOT NULL,
    flood_wait_until timestamp with time zone,
    last_join_at timestamp with time zone,
    next_join_allowed_at timestamp with time zone,
    daily_reset_at timestamp with time zone,
    channels_count integer DEFAULT 0 NOT NULL,
    is_premium boolean DEFAULT false NOT NULL,
    device_model text,
    system_version text,
    app_version text,
    system_lang_code text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.accounts_id_seq OWNED BY public.accounts.id;


--
-- Name: accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts ALTER COLUMN id SET DEFAULT nextval('public.accounts_id_seq'::regclass);


--
-- Name: accounts accounts_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_phone_key UNIQUE (phone);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict evt5EBCNejPMFOSBNXeLMLQsTxm7FXqK6rNVOHh2SpKEZJpQdM2Uxt4scqTqRPJ

--
-- PostgreSQL database dump
--

\restrict Bp6edzrRuqIReTm0EqfZo36hIaT8HoYS5cmiS5Xw16sANT8gOM9DHZUGJU1LOKO

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bot_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_state (
    id integer NOT NULL,
    running boolean DEFAULT false NOT NULL,
    current_account_id integer,
    started_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: bot_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bot_state_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bot_state_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bot_state_id_seq OWNED BY public.bot_state.id;


--
-- Name: bot_state id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_state ALTER COLUMN id SET DEFAULT nextval('public.bot_state_id_seq'::regclass);


--
-- Name: bot_state bot_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_state
    ADD CONSTRAINT bot_state_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict Bp6edzrRuqIReTm0EqfZo36hIaT8HoYS5cmiS5Xw16sANT8gOM9DHZUGJU1LOKO

--
-- PostgreSQL database dump
--

\restrict oZxJVoo4uASIr1xPlxCVqfGKbM2zkYOFXtPH5TH9UtFkOGwWkN9S9JvFl65HH6p

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: group_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_links (
    id integer NOT NULL,
    url text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    fail_reason text,
    group_title text,
    group_type text,
    source text,
    used_by_account_id integer,
    retry_count integer DEFAULT 0 NOT NULL,
    retry_after timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);


--
-- Name: group_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.group_links_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: group_links_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.group_links_id_seq OWNED BY public.group_links.id;


--
-- Name: group_links id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_links ALTER COLUMN id SET DEFAULT nextval('public.group_links_id_seq'::regclass);


--
-- Name: group_links group_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_links
    ADD CONSTRAINT group_links_pkey PRIMARY KEY (id);


--
-- Name: group_links group_links_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_links
    ADD CONSTRAINT group_links_url_key UNIQUE (url);


--
-- PostgreSQL database dump complete
--

\unrestrict oZxJVoo4uASIr1xPlxCVqfGKbM2zkYOFXtPH5TH9UtFkOGwWkN9S9JvFl65HH6p

--
-- PostgreSQL database dump
--

\restrict MYng5jzonbpPw9Hlln6Lulv7NlPrCwb0StCaFacWXCN7nRXLTe8O8ONYUCplPQM

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id integer NOT NULL,
    name text NOT NULL,
    connection_string text NOT NULL,
    db_name text NOT NULL,
    link_field text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    last_sync_at timestamp with time zone,
    synced_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.collections_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: collections_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.collections_id_seq OWNED BY public.collections.id;


--
-- Name: collections id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections ALTER COLUMN id SET DEFAULT nextval('public.collections_id_seq'::regclass);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict MYng5jzonbpPw9Hlln6Lulv7NlPrCwb0StCaFacWXCN7nRXLTe8O8ONYUCplPQM

--
-- PostgreSQL database dump
--

\restrict 5e7OZGrGBgvMnEngCrtNu5GuuK7zascWtVycnJMHum7QMl2GgEyNs34gaqUI44K

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_log (
    id integer NOT NULL,
    type text NOT NULL,
    message text NOT NULL,
    account_phone text,
    link_url text,
    error_code text,
    wait_seconds integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.activity_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: activity_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.activity_log_id_seq OWNED BY public.activity_log.id;


--
-- Name: activity_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log ALTER COLUMN id SET DEFAULT nextval('public.activity_log_id_seq'::regclass);


--
-- Name: activity_log activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 5e7OZGrGBgvMnEngCrtNu5GuuK7zascWtVycnJMHum7QMl2GgEyNs34gaqUI44K

--
-- PostgreSQL database dump
--

\restrict f44opyXn2XK5ARafZ2Jl5fBQO1f83aUtxj92MqrnInQ9a5cXeYf9NiAfPCERiZe

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: join_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.join_jobs (
    id integer NOT NULL,
    account_id integer NOT NULL,
    link_id integer NOT NULL,
    status text NOT NULL,
    error_code text,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: join_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.join_jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: join_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.join_jobs_id_seq OWNED BY public.join_jobs.id;


--
-- Name: join_jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.join_jobs ALTER COLUMN id SET DEFAULT nextval('public.join_jobs_id_seq'::regclass);


--
-- Name: join_jobs join_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.join_jobs
    ADD CONSTRAINT join_jobs_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict f44opyXn2XK5ARafZ2Jl5fBQO1f83aUtxj92MqrnInQ9a5cXeYf9NiAfPCERiZe

--
-- PostgreSQL database dump
--

\restrict esRY7W0RJHirwNB9yOJpkQLmVsvjQB2VX9RBnUv1dxv5gWTz1SGTUgcsCLG9ZTR

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: channel_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.channel_links (
    id integer NOT NULL,
    url text NOT NULL,
    title text,
    detected_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: channel_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.channel_links_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: channel_links_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.channel_links_id_seq OWNED BY public.channel_links.id;


--
-- Name: channel_links id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_links ALTER COLUMN id SET DEFAULT nextval('public.channel_links_id_seq'::regclass);


--
-- Name: channel_links channel_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_links
    ADD CONSTRAINT channel_links_pkey PRIMARY KEY (id);


--
-- Name: channel_links channel_links_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_links
    ADD CONSTRAINT channel_links_url_key UNIQUE (url);


--
-- PostgreSQL database dump complete
--

\unrestrict esRY7W0RJHirwNB9yOJpkQLmVsvjQB2VX9RBnUv1dxv5gWTz1SGTUgcsCLG9ZTR

--
-- PostgreSQL database dump
--

\restrict PrjscmnpBNhh0vwfNFkHaeMZeP1ricNXrh3Mqf1OOboUBlw60lTj9TBpJFWF7vH

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- PostgreSQL database dump complete
--

\unrestrict PrjscmnpBNhh0vwfNFkHaeMZeP1ricNXrh3Mqf1OOboUBlw60lTj9TBpJFWF7vH
