/**
 * EXPORT DATABASE FOR MIGRATION
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run export-db
 *
 * Outputs two files in the project root:
 *   schema.sql  — CREATE TABLE statements (always)
 *   data.sql    — INSERT statements for all rows (if any data exists)
 */

import { execSync } from "child_process";
import { writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const DATABASE_URL = process.env["DATABASE_URL"];
if (!DATABASE_URL) {
  console.error("❌ DATABASE_URL env var is required");
  process.exit(1);
}

const TABLES = [
  "accounts",
  "bot_state",
  "group_links",
  "collections",
  "activity_log",
  "join_jobs",
  "channel_links",
  "settings",
];

function run(cmd: string): string {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim();
  } catch (e: any) {
    throw new Error(`Command failed: ${cmd}\n${e.stderr ?? e.message}`);
  }
}

function psql(query: string): string {
  return run(
    `psql "${DATABASE_URL}" -t -A -c ${JSON.stringify(query)}`
  );
}

console.log("📦 Exporting database schema and data...\n");

// ── Schema export ──────────────────────────────────────────────────────────
const schemaLines: string[] = [
  "-- Schema export generated by export-db script",
  `-- Date: ${new Date().toISOString()}`,
  "",
];

for (const table of TABLES) {
  console.log(`  📋 Schema: ${table}`);
  try {
    const ddl = run(
      `pg_dump "${DATABASE_URL}" --schema-only --table=${table} --no-owner --no-acl`
    );
    schemaLines.push(ddl, "");
  } catch {
    // pg_dump not available, build CREATE TABLE manually from information_schema
    schemaLines.push(`-- Table: ${table}`);
    const cols = psql(
      `SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
       FROM information_schema.columns
       WHERE table_name = '${table}'
       ORDER BY ordinal_position`
    );
    const colDefs = cols
      .split("\n")
      .filter(Boolean)
      .map((row) => {
        const [name, type, maxLen, nullable, def] = row.split("|");
        let colDef = `  ${name} ${type}${maxLen ? `(${maxLen})` : ""}`;
        if (def && def !== "") colDef += ` DEFAULT ${def}`;
        if (nullable === "NO") colDef += " NOT NULL";
        return colDef;
      });
    schemaLines.push(
      `CREATE TABLE IF NOT EXISTS ${table} (`,
      colDefs.join(",\n"),
      ");",
      ""
    );
  }
}

const schemaPath = path.join(ROOT, "schema.sql");
writeFileSync(schemaPath, schemaLines.join("\n"));
console.log(`\n✅ Schema saved → schema.sql`);

// ── Data export ────────────────────────────────────────────────────────────
const dataLines: string[] = [
  "-- Data export generated by export-db script",
  `-- Date: ${new Date().toISOString()}`,
  "",
];

let totalRows = 0;

for (const table of TABLES) {
  let count = "0";
  try {
    count = psql(`SELECT COUNT(*) FROM ${table}`);
  } catch {
    continue;
  }

  const n = parseInt(count, 10);
  console.log(`  📊 Data: ${table} — ${n} rows`);

  if (n === 0) continue;
  totalRows += n;

  try {
    const copyOut = run(
      `psql "${DATABASE_URL}" -c "\\COPY ${table} TO STDOUT WITH (FORMAT csv, HEADER true)"`
    );
    const rows = copyOut.split("\n").filter(Boolean);
    const headers = rows[0].split(",");
    const values = rows.slice(1);

    dataLines.push(`-- ${table} (${n} rows)`);
    for (const row of values) {
      dataLines.push(
        `INSERT INTO ${table} (${headers.join(", ")}) VALUES (${row}) ON CONFLICT DO NOTHING;`
      );
    }
    dataLines.push("");
  } catch {
    dataLines.push(`-- Skipped ${table}: could not export rows`);
    dataLines.push("");
  }
}

const dataPath = path.join(ROOT, "data.sql");
writeFileSync(dataPath, dataLines.join("\n"));
console.log(`\n✅ Data saved → data.sql (${totalRows} total rows)`);
console.log("\n📁 Files ready for migration:");
console.log("   schema.sql — run this first on the new database");
console.log("   data.sql   — run this after schema to restore data");
console.log("\nOn Railway, set DATABASE_URL then run:");
console.log("   psql $DATABASE_URL < schema.sql");
console.log("   psql $DATABASE_URL < data.sql");
